### ISSUE TITLE
Замечания и рекомендации по lw5 - MiniBlog

### ISSUE THREAD

**Issue by ivklgn** [Rechkanet/Mini-Blog#1]
**Интерфейс и сценарий использования:**
1. При нахождении на главной странице (публикаций нет) - кнопка добавить - имеет непонятное назначение - добавить лэйбл или переименовать
2. При добавлении публикации - если поля не заполнены - происходит переход на главную страницу. Сделать понятное сообщение о вводе обязательным полей
3. Если мы добавили запись в блок, потом переходим на нее через кнопку Подробнее - непонятно, почему открывается редактирование записи? - сделать отдельные маршруты для просмотра записи и для редактирования

**Архитектура приложения:**
1. При использовании React - неверно сделано разделение контейнеров и компонентов. Пример:
![image](https://user-images.githubusercontent.com/15219574/37207640-ea0e8502-23ae-11e8-8029-732f01162c01.png)
каждая запись блока - это компонента. Листинг записей блоков - это тоже компонента
см. https://maxfarseer.gitbooks.io/react-course-ru/content/
см. примеры на гитхабе из курса - https://maxfarseer.gitbooks.io/redux-course-ru/content/
2. Проверить свой код по этим замечаниям: https://github.com/artes2517/Telegraph/issues/1
3. Вынести навигационную панель в отдельную компоненту
![image](https://user-images.githubusercontent.com/15219574/37207747-67e3e8fa-23af-11e8-9c91-ed5f5bc3e1f4.png)
4. Вместо объявления состояния по умолчанию в конструкторе компонента:
```js
    this.state = {
      title: '',
      discription: '',
      date: null
    };
```
используйте getInitialState
-------------
- углубитесь в правильность оформления и описания, разбивки интерфейса на компоненты, добейтесь повторного использования компонент в приложении

kQ=0.4

**Comment by Rechkanet** [comment]
Исправил замечания. Проверьте, пожалуйста.

**Comment by Rechkanet** [comment]
Оставил определение state в конструкторе. Т.к React на ES6+.
Исходя из статей:
https://reactjs.org/docs/state-and-lifecycle.html
https://habrahabr.ru/post/262183/

**Comment by ivklgn** [comment]
1. При нахождении на главной странице (публикаций нет) - кнопка добавить - имеет непонятное назначение - добавить лэйбл или переименовать
>> добавить лэйбл - не означает добавить слово label в кнопку. Замечание касалось того, что кнопка с текстом "Добавить" была непонятно для добавления чего. Достаточно назвать кнопку "Добавить новость"
2. Определится с языком в интерфейсе - либо все поля и подписи на английском или всё переписать на русский
---------
остальное ОК

kQ=0.8

**Comment by Rechkanet** [comment]
Исправил замечания. Проверьте, пожалуйста.
